### PR TITLE
Install libcurl

### LINKED ISSUE #76: Install libcurl4-openssl-dev
Fastlane dependency `curb` requires `libcurl4-openssl-dev`.

It can be installed using:
`apt-get -y install libcurl4-openssl-dev`

### PR DESCRIPTION
**Pull request by sjcqs**
fix #76

### CODE REVIEW

**Comment by sjcqs** [comment]
You're right. 

Plus, libcurl is needed because of fastlane which has the built-in badge action (to add beta badge to app icon).
Badge requires curb which requires the libcurl.

Extract from `gem dependency`:
```
Gem badge-0.12.0
  curb (~> 0.9)
  fastimage (>= 1.6)
  fastlane (>= 2.0)
  mini_magick (>= 4.9.4, < 5.0.0)
```

**Comment by sjcqs** [comment]
I just notice that we were already running tests using fastlane. 

Why would `bundle install` fail only when I tried to build our internal android project and not here ?

**Comment by vincentbrison** [comment]
The idea behind that is we have many dependencies installed through apt, and even if they are not documented, removing one of them should at least directly break something, like build or tests.

**Comment by vincentbrison** [comment]
(I am not sure this is the case right now but, we should try to move into this direction I guess)

**Comment by vincentbrison** [comment]
Maybe because the bundle install we do does not require `badge-0.12.0` ?

**Comment by sjcqs** [comment]
Installing libcurl is only required if `gem 'fastlane-plugin-badge'` is used. (which is only used by the iOS part of ADFastlane)
`tests` here are not using it. 

If we add libcurl to support `fastlane-plugin-badge` then it means we'll have to try each and every fastlane plugins our there.

It might be the responsability of the consumer to install missing dependencies ? 🤷

**Comment by vincentbrison** [comment]
As we want our images to have first class support for Fastlane, we could keep an issue opened, where we track missing native dependencies, alongside with some explanation on how to install those dependencies manually. Then we will figure if those native libs should be part of our images. What do you think about that?

**Comment by sjcqs** [comment]
@vincentbrison our Github Action tests will fail until images with the missing lib will be uploaded to docker hub.

**Comment by vincentbrison** [comment]
Yes, I do not know how to address this yet. We might rethink or split the tests for the action, as we do not need the same feature covering as the base image, and the tests of the images will always be ahead of time of the release of the image. I will make an issue for this.

**Comment by vincentbrison** [comment]
@sjcqs I created #79 to work on this.

**Pull request merged**
